# Author: noraj
version: '3'
services:
  haiti:
    image: noraj/haiti:2.0.0
    user: noraj
    container_name: haiti
    read_only: false
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HAITI_VERSION: 2.0.0
